#!/usr/bin/env python3
"""Materialize bounded path-resolved edge examples directly from a GBZ.

``vg paths`` can stream selected GBZ paths as GAF, but writing the complete
expanded GAF for a whole human cohort is unnecessarily expensive.  This tool
consumes that stream directly and retains a deterministic, bounded set of true
path adjacencies per path and coordinate window.  Every row keeps donor,
haplotype, locus, and donor-split provenance.

The output contains positive path-continuity examples only.  It deliberately
does not invent negatives: valid haplotype-specific negatives require testing
aggregate-graph edges that are absent from the focal path and are generated by
a separate task builder.
"""

from __future__ import annotations

import argparse
import csv
import gzip
import hashlib
import heapq
import io
import json
import shlex
import subprocess
import time
from pathlib import Path
from typing import Iterable, TextIO

import pandas as pd


CANONICAL_CHROMOSOMES = {f"chr{index}" for index in range(1, 23)} | {"chrX", "chrY", "chrM"}


def canonical_chromosome(value: object) -> str:
    raw = str(value)
    # Haplotype paths may append a phase-block coordinate after the
    # chromosome, for example HG002#1#chr22#13698806. Prefer an explicit
    # ``chr*`` token: the preceding bare numeric token is a haplotype, not a
    # chromosome.
    tokens = raw.replace("|", "#").split("#")
    for token in tokens:
        candidate = token.split("[", 1)[0]
        if candidate in CANONICAL_CHROMOSOMES:
            return candidate

    fallback = tokens[-1].split("[", 1)[0]
    if fallback in {*(str(index) for index in range(1, 23)), "X", "Y", "M", "MT"}:
        return "chrM" if fallback in {"M", "MT"} else f"chr{fallback}"
    return fallback


def iter_path_handles(path_field: str) -> Iterable[tuple[str, str]]:
    """Yield ``(segment_name, orientation)`` from a GAF walk string."""

    index = 0
    while index < len(path_field):
        marker = path_field[index]
        if marker not in "><":
            raise ValueError(f"Unsupported GAF path encoding near {path_field[index:index + 40]!r}")
        end = index + 1
        while end < len(path_field) and path_field[end] not in "><":
            end += 1
        name = path_field[index + 1 : end]
        if not name:
            raise ValueError("Empty segment name in GAF path")
        yield name, "+" if marker == ">" else "-"
        index = end


def stable_rank(*parts: object) -> int:
    payload = "\x1f".join(map(str, parts)).encode("utf-8")
    return int.from_bytes(hashlib.blake2b(payload, digest_size=8).digest(), "big")


def open_deterministic_gzip_text(path: Path) -> TextIO:
    raw = path.open("wb")
    compressed = gzip.GzipFile(filename="", mode="wb", fileobj=raw, mtime=0)
    return io.TextIOWrapper(compressed, encoding="utf-8", newline="")


def load_path_records(
    path: Path,
    *,
    chromosomes: set[str] | None,
    splits: set[str],
    max_paths: int | None,
) -> pd.DataFrame:
    frame = pd.read_csv(path, compression="infer")
    required = {"donor_split", "sample", "haplotype", "locus", "path_name"}
    missing = required - set(frame.columns)
    if missing:
        raise ValueError(f"Path records miss columns: {sorted(missing)}")
    frame = frame.loc[frame["donor_split"].astype(str).isin(splits)].copy()
    locus_chromosome = frame["locus"].map(canonical_chromosome)
    path_chromosome = frame["path_name"].map(canonical_chromosome)
    # GBZ metadata from some releases uses assembly-contig identifiers in
    # LOCUS even when the canonical chromosome remains encoded in #NAME.
    # Prefer canonical LOCUS values, then fall back to the path name.
    frame["chromosome"] = locus_chromosome.where(
        locus_chromosome.isin(CANONICAL_CHROMOSOMES),
        path_chromosome,
    )
    if chromosomes:
        frame = frame.loc[frame["chromosome"].isin(chromosomes)].copy()
    frame = frame.drop_duplicates("path_name").sort_values("path_name").reset_index(drop=True)
    if max_paths is not None:
        frame = frame.head(max_paths).copy()
    if frame.empty:
        raise ValueError("No path records remain after filtering")
    return frame


def load_segments(path: Path) -> tuple[dict[str, tuple[int, int]], str]:
    frame = pd.read_csv(path, compression="infer", usecols=["id", "name", "LN"])
    if frame["name"].duplicated().any():
        raise ValueError("full_segments has duplicate segment names")
    lookup = {
        str(row.name): (int(row.id), int(row.LN))
        for row in frame.itertuples(index=False)
    }
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(8 * 1024 * 1024):
            digest.update(chunk)
    return lookup, digest.hexdigest()


def oid(segid: int, orientation: str) -> int:
    return 2 * int(segid) + int(orientation == "-")


def stream_examples(
    gaf: TextIO,
    *,
    metadata: dict[str, dict[str, object]],
    segments: dict[str, tuple[int, int]],
    writer: csv.DictWriter,
    window_bp: int,
    edges_per_window: int,
) -> dict[str, int]:
    counters = {
        "gaf_records": 0,
        "selected_gaf_records": 0,
        "malformed_gaf_records": 0,
        "handles_seen": 0,
        "missing_segment_handles": 0,
        "path_edges_seen": 0,
        "sampled_positive_edges": 0,
    }
    for line in gaf:
        if not line.strip() or line.startswith("#"):
            continue
        counters["gaf_records"] += 1
        fields = line.rstrip("\n").split("\t")
        if len(fields) < 6:
            counters["malformed_gaf_records"] += 1
            continue
        path_name = fields[0]
        record = metadata.get(path_name)
        if record is None:
            # Some vg versions normalize a no-subrange path name.  The caller
            # still receives an exact audit instead of silently assigning it.
            continue
        try:
            query_start = int(fields[2])
        except ValueError:
            counters["malformed_gaf_records"] += 1
            continue
        counters["selected_gaf_records"] += 1
        heaps: dict[int, list[tuple[int, tuple[object, ...]]]] = {}
        previous: tuple[str, str, int, int] | None = None
        path_position = query_start
        edge_index = 0
        try:
            handles = iter_path_handles(fields[5])
            for name, orientation in handles:
                counters["handles_seen"] += 1
                segment = segments.get(name)
                if segment is None:
                    counters["missing_segment_handles"] += 1
                    previous = None
                    continue
                segid, length = segment
                current = (name, orientation, segid, path_position)
                if previous is not None:
                    counters["path_edges_seen"] += 1
                    window_index = max(previous[3], 0) // window_bp
                    rank = stable_rank(
                        path_name,
                        window_index,
                        edge_index,
                        previous[0],
                        previous[1],
                        name,
                        orientation,
                    )
                    payload = (
                        record.get("dataset", ""),
                        record["donor_split"],
                        record["sample"],
                        record["haplotype"],
                        record["locus"],
                        record["chromosome"],
                        path_name,
                        window_index * window_bp,
                        (window_index + 1) * window_bp,
                        edge_index,
                        previous[3],
                        previous[0],
                        previous[1],
                        oid(previous[2], previous[1]),
                        name,
                        orientation,
                        oid(segid, orientation),
                        rank,
                    )
                    heap = heaps.setdefault(window_index, [])
                    item = (-rank, payload)
                    if len(heap) < edges_per_window:
                        heapq.heappush(heap, item)
                    elif item > heap[0]:
                        heapq.heapreplace(heap, item)
                    edge_index += 1
                previous = current
                path_position += length
        except ValueError:
            counters["malformed_gaf_records"] += 1
            continue

        for window_index in sorted(heaps):
            rows = sorted((-neg_rank, payload) for neg_rank, payload in heaps[window_index])
            for _, payload in rows:
                writer.writerow(dict(zip(writer.fieldnames or [], payload)))
                counters["sampled_positive_edges"] += 1
    return counters


def materialize(
    *,
    gbz: Path | None,
    gaf_input: Path | None,
    path_records: Path,
    full_segments: Path,
    out_dir: Path,
    chromosomes: set[str] | None,
    splits: set[str],
    max_paths: int | None,
    window_bp: int,
    edges_per_window: int,
    vg_executable: str,
) -> dict[str, object]:
    if out_dir.exists() and any(out_dir.iterdir()):
        raise FileExistsError(f"Output directory is not empty: {out_dir}")
    out_dir.mkdir(parents=True, exist_ok=True)
    selected = load_path_records(
        path_records,
        chromosomes=chromosomes,
        splits=splits,
        max_paths=max_paths,
    )
    path_list = out_dir / "selected_paths.txt"
    path_list.write_text("\n".join(selected["path_name"].astype(str)) + "\n")
    selected.to_csv(out_dir / "selected_path_records.csv.gz", index=False, compression="gzip")
    metadata = {
        str(row.path_name): row._asdict()
        for row in selected.itertuples(index=False)
    }
    segments, segments_sha256 = load_segments(full_segments)
    command: list[str] | None = None
    process: subprocess.Popen[str] | None = None
    if gaf_input is not None:
        gaf_handle = gzip.open(gaf_input, "rt") if gaf_input.suffix == ".gz" else gaf_input.open()
    else:
        if gbz is None:
            raise ValueError("Either gbz or gaf_input is required")
        command = [vg_executable, "paths", "-x", str(gbz), "-p", str(path_list), "-A"]
        process = subprocess.Popen(
            command,
            stdout=subprocess.PIPE,
            stderr=(out_dir / "vg_paths.stderr.log").open("w"),
            text=True,
            encoding="utf-8",
            errors="replace",
        )
        if process.stdout is None:
            raise RuntimeError("vg paths stdout pipe was not created")
        gaf_handle = process.stdout

    fieldnames = [
        "dataset", "donor_split", "sample", "haplotype", "locus", "chromosome",
        "path_name", "window_start", "window_end", "path_edge_index", "path_position",
        "u_segment", "u_orientation", "u_oid", "v_segment", "v_orientation", "v_oid",
        "deterministic_rank",
    ]
    output = out_dir / "positive_path_edges.csv.gz"
    started = time.monotonic()
    with gaf_handle, open_deterministic_gzip_text(output) as output_handle:
        writer = csv.DictWriter(output_handle, fieldnames=fieldnames)
        writer.writeheader()
        counters = stream_examples(
            gaf_handle,
            metadata=metadata,
            segments=segments,
            writer=writer,
            window_bp=window_bp,
            edges_per_window=edges_per_window,
        )
    if process is not None:
        returncode = process.wait()
        if returncode != 0:
            raise RuntimeError(f"vg paths failed with exit code {returncode}")

    donor_split_counts = (
        selected[["sample", "donor_split"]]
        .drop_duplicates()
        .groupby("donor_split")["sample"]
        .nunique()
        .to_dict()
    )
    missing_fraction = (
        counters["missing_segment_handles"] / counters["handles_seen"]
        if counters["handles_seen"]
        else 1.0
    )
    payload = {
        "schema_version": 1,
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S%z"),
        "status": "complete" if counters["sampled_positive_edges"] > 0 and missing_fraction <= 1e-6 else "audit_warning",
        "gbz": str(gbz.resolve()) if gbz else None,
        "gaf_input": str(gaf_input.resolve()) if gaf_input else None,
        "vg_command": shlex.join(command) if command else None,
        "path_records": str(path_records.resolve()),
        "full_segments": str(full_segments.resolve()),
        "full_segments_sha256": segments_sha256,
        "selected_path_count": int(len(selected)),
        "selected_donor_count": int(selected["sample"].nunique()),
        "selected_haplotype_count": int(selected[["sample", "haplotype"]].drop_duplicates().shape[0]),
        "selected_chromosomes": sorted(selected["chromosome"].unique()),
        "donor_split_counts": {str(key): int(value) for key, value in donor_split_counts.items()},
        "window_bp": window_bp,
        "maximum_positive_edges_per_path_window": edges_per_window,
        "counters": counters,
        "missing_segment_handle_fraction": missing_fraction,
        "output": str(output.resolve()),
        "output_bytes": output.stat().st_size,
        "wall_seconds": time.monotonic() - started,
        "leakage_policy": "donor_split is inherited from a one-donor-one-split manifest",
        "negative_example_policy": "not generated; haplotype-specific absent-edge negatives require an aggregate-edge/path-membership join",
    }
    (out_dir / "audit.json").write_text(json.dumps(payload, indent=2) + "\n")
    return payload


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--gbz", type=Path)
    source.add_argument("--gaf-input", type=Path)
    parser.add_argument("--path-records", type=Path, required=True)
    parser.add_argument("--full-segments", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, required=True)
    parser.add_argument("--chromosomes", nargs="*")
    parser.add_argument("--splits", nargs="+", default=["train", "validation", "test"])
    parser.add_argument("--max-paths", type=int)
    parser.add_argument("--window-bp", type=int, default=5_000_000)
    parser.add_argument("--edges-per-window", type=int, default=16)
    parser.add_argument("--vg-executable", default="vg")
    args = parser.parse_args()
    if args.window_bp <= 0 or args.edges_per_window <= 0:
        parser.error("window and edge limits must be positive")
    payload = materialize(
        gbz=args.gbz,
        gaf_input=args.gaf_input,
        path_records=args.path_records,
        full_segments=args.full_segments,
        out_dir=args.out_dir,
        chromosomes={canonical_chromosome(value) for value in args.chromosomes} if args.chromosomes else None,
        splits=set(args.splits),
        max_paths=args.max_paths,
        window_bp=args.window_bp,
        edges_per_window=args.edges_per_window,
        vg_executable=args.vg_executable,
    )
    print(json.dumps(payload, indent=2))
    return 0 if payload["status"] == "complete" else 1


if __name__ == "__main__":
    raise SystemExit(main())
