"""Render completed-study table rows from the immutable manuscript evidence bundle.

This formats archived estimates and intervals; it neither refits models nor reads
live/partial chromosome replication outputs. Run from any working directory.
"""
from pathlib import Path
import hashlib
import json

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent
EVIDENCE = ROOT / 'evidence' / 'completed_20260928'


def one(frame, **where):
    selected = frame
    for key, value in where.items():
        selected = selected.loc[selected[key].eq(value)]
    if len(selected) != 1:
        raise ValueError(f'Expected one row for {where}, got {len(selected)}')
    return selected.iloc[0]


def interval(row):
    return f"[{row['ci95_low']:+.6f}, {row['ci95_high']:+.6f}]"


def write_rows(name, rows):
    (ROOT / name).write_text(
        '% Generated by build_completed_evidence.py from completed_20260928.\n'
        + '\n'.join(' & '.join(row) + r' \\' for row in rows) + '\n'
    )


def build():
    manifest = json.loads((EVIDENCE / 'provenance.json').read_text())
    for name, info in manifest['sources'].items():
        actual = hashlib.sha256((EVIDENCE / name).read_bytes()).hexdigest()
        if actual != info['snapshot_sha256']:
            raise ValueError(f'Evidence snapshot changed: {name}')
    natural_audit = json.loads((EVIDENCE / 'sv_natural_audit.json').read_text())
    if not (natural_audit['status'] == 'complete'
            and natural_audit['n_runs'] == 30
            and natural_audit['n_evaluations'] == 1170
            and natural_audit['n_excluded'] == 0
            and natural_audit['all_metrics_replayed']
            and natural_audit['all_probes_converged']):
        raise ValueError('Natural SV completion gate failed')
    development = json.loads((EVIDENCE / 'development_audit.json').read_text())
    if not (development['all_declared_seeds_complete']
            and development['all_metrics_replayed']
            and development['all_probes_converged']):
        raise ValueError('Development completion gate failed')

    scorecard = pd.read_csv(EVIDENCE / 'downstream_scorecard.csv')
    if not np.allclose(scorecard.cst_auprc - scorecard.cs_auprc,
                       scorecard.delta_t, atol=1e-12, rtol=0):
        raise ValueError('Scorecard paired mean mismatch')
    entex_tasks = {
        'P0 AS-prone cCRE': 'AS-prone cCRE',
        'P0 exposure matched': 'P0 exposure matched',
        'P0 H3K27ac only': 'P0 H3K27ac only',
        'P0 CTCF only': 'P0 CTCF only',
        'P1 enhancer tissue macro': 'Enhancer tissue macro',
        'P2 CTCF SNV': 'CTCF SNV',
        'P2 H3K27ac SNV': 'H3K27ac SNV',
        'RNA ASE SNV': 'RNA ASE SNV',
        'P2 ATAC SNV': 'ATAC SNV',
        'P2 H3K4ME3 SNV': 'H3K4me3 SNV',
        'P2 H3K27ME3 SNV': 'H3K27me3 SNV',
    }
    rows = []
    for task, label in entex_tasks.items():
        for context in ['strict', '1hop']:
            row = one(scorecard, task=task, context=context)
            rows.append([label, context.replace('1hop', '1-hop'),
                         f'{row.cs_auprc:.4f}', f'{row.cst_auprc:.4f}',
                         f'{row.delta_t:+.5f}',
                         f'[{row.ci95_low:+.5f}, {row.ci95_high:+.5f}]'])
    write_rows('entex_completed_rows.tex', rows)

    natural = pd.read_csv(EVIDENCE / 'sv_natural_ap.csv')
    absolute = pd.read_csv(EVIDENCE / 'sv_natural_absolute_ap.csv')
    rows = []
    for target in ['macro', 'INV']:
        for contrast, base, full in [('T_given_CS', 'coordinate_plus_frozen_sequence_fm',
                                      'coordinate_plus_frozen_sequence_fm_plus_frozen_pangenomefm'),
                                     ('T_given_CSLH', 'CSLH', 'CSLHT')]:
            for context in ['strict', '1hop']:
                row = one(natural, target_class=target, contrast=contrast, context=context)
                baseline = one(absolute, target_class=target, feature_set=base,
                               context=context)['mean']
                model = one(absolute, target_class=target, feature_set=full,
                            context=context)['mean']
                if not np.isclose(model - baseline, row['mean'], atol=1e-12, rtol=0):
                    raise ValueError('Natural SV paired mean mismatch')
                rows.append([target.capitalize() if target == 'macro' else target,
                             context.replace('1hop', '1-hop'),
                             '$C+S$' if contrast == 'T_given_CS' else '$C+S+L+H$',
                             f'{baseline:.6f}', f'{model:.6f}',
                             f"{row['mean']:+.6f}", interval(row)])
    write_rows('sv_natural_rows.tex', rows)

    matched = pd.read_csv(EVIDENCE / 'sv_matched_ap.csv')
    rows = []
    for contrast, label in [('T_given_CS', '$C+S$'), ('T_given_CSH', '$C+S+H$')]:
        for context in ['strict', '1hop']:
            row = one(matched, target_class='macro', context=context, contrast=contrast)
            rows.append([label, context.replace('1hop', '1-hop'),
                         f"{row['mean']:+.6f}", interval(row),
                         f'{row.sign_flip_p:.4f}', f'{row.bh_q_within_metric:.4f}'])
    write_rows('sv_matched_rows.tex', rows)

    hr = pd.read_csv(EVIDENCE / 'hr_ap.csv')
    rows = []
    for task, label in [('sv', 'INS/DEL'), ('ccre', 'cCRE')]:
        for context in ['strict', '1hop']:
            row = one(hr, task=task, context=context, contrast='T_minus_R_given_CSH')
            rows.append([label, context.replace('1hop', '1-hop'),
                         f"{row['mean']:+.6f}", interval(row),
                         f'{row.sign_flip_p:.4f}', f'{row.bh_q_within_metric:.4f}'])
    write_rows('hr_completed_rows.tex', rows)

    development = pd.read_csv(EVIDENCE / 'development_ap.csv')
    rows = []
    for seed in [42, 314159, 20260806]:
        for task, label in [('sv', 'INS/DEL'), ('ccre', 'cCRE')]:
            trained = one(development, seed=seed, task=task, feature='csht',
                          comparison='full_trained minus full_random')
            coordinate = one(development, seed=seed, task=task, feature='csht',
                             comparison='full_trained minus coordinate_trained')
            rows.append([str(seed), label, f'{trained.candidate:.6f}',
                         f'{trained.control:.6f}', f'{trained.difference:+.6f}',
                         f'{coordinate.difference:+.6f}'])
    write_rows('development_rows.tex', rows)
    rows = []
    for context in ['strict', '1hop']:
        row = one(scorecard, task='HG008 clonal INS versus DEL', context=context)
        rows.append(['HG008 INS/DEL', context.replace('1hop', '1-hop'), 'AP gain',
                     f'{row.delta_t:+.6f}', interval(row)])
    traitgym = pd.read_csv(EVIDENCE / 'traitgym_primary_ap.csv')
    for dataset, label in [('complex_traits', 'TraitGym complex'),
                           ('mendelian_traits', 'TraitGym Mendelian')]:
        for context in ['strict', '1hop']:
            row = one(traitgym, dataset=dataset, context=context, contrast='T_given_CS')
            rows.append([label, context.replace('1hop', '1-hop'), 'AP gain',
                         f"{row['mean']:+.6f}", interval(row)])
    cosigt = pd.read_csv(EVIDENCE / 'cosigt_primary_mae.csv')
    for context in ['strict', '1hop']:
        row = one(cosigt, context=context, contrast='T_given_CS')
        rows.append(['COSIGT QV fraction', context.replace('1hop', '1-hop'),
                     'MAE reduction', f"{row['mean']:+.6f}", interval(row)])
    write_rows('transfer_boundary_rows.tex', rows)
    print('Verified bundled evidence and generated six completed-study tables.')


if __name__ == '__main__':
    build()
