"""Derive namespaced supplement entries from the single maintained bibliography.

multibib/natbib otherwise reuse citation labels and PDF anchors when a work is
cited in both bibliographies. Only keys differ; bibliographic fields stay exact.
"""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent


def main() -> None:
    source = (ROOT / "references.bib").read_text()
    texts = [(ROOT / "main.tex").read_text().split(r"\appendix", 1)[1]]
    texts.append((ROOT / "completed_supplement_20260928.tex").read_text())
    keys = {
        key.strip()
        for text in texts
        for group in re.findall(r"\\citepS\{([^}]+)\}", text)
        for key in group.split(",")
    }
    entries = {}
    # Every maintained entry starts at column zero, so splitting at the next
    # entry preserves nested author accents and all other BibTeX field syntax.
    for entry in re.split(r"(?m)(?=^@)", source):
        match = re.match(r"@\w+\{([^,]+),", entry)
        if match:
            entries["supp__" + match[1]] = entry.replace(
                "{" + match[1] + ",", "{supp__" + match[1] + ",", 1
            ).strip()
    if not keys or not keys <= entries.keys():
        raise ValueError(f"Missing supplementary citations: {keys - entries.keys()}")
    output = "% Generated by build_supplement_references.py; edit references.bib.\n\n"
    output += "\n\n".join(entries[key] for key in sorted(keys)) + "\n"
    (ROOT / "supplement_references.bib").write_text(output)
    print(f"Generated {len(keys)} uniquely linked supplementary references.")


if __name__ == "__main__":
    main()
