#!/usr/bin/env python3
"""Build the two standalone downstream-result charts for the T2T poster."""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.colors import LinearSegmentedColormap


TEMPLE_CHERRY = "#A41E35"
TEMPLE_DARK = "#7A0019"
TEMPLE_LIGHT = "#D24A61"
NEUTRAL_DARK = "#777777"
NEUTRAL_LIGHT = "#B8B8B8"
GRID = "#E3E3E3"
TEXT = "#171717"


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source",
        type=Path,
        default=Path(
            "server_imports/sequence_fm_v2_20260817/extracted/"
            "manuscript_sequence_fm_outputs_20260817/"
            "manuscript_sequence_fm_absolute_performance.csv"
        ),
        help="Absolute-performance table generated by the manuscript analysis.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("output/poster_t2t_20260831/downstream_bar_charts"),
    )
    parser.add_argument("--dpi", type=int, default=400)
    return parser


def _read_values(path: Path, task: str) -> tuple[list[float], list[float]]:
    table = pd.read_csv(path)
    task_rows = table[(table["task"] == task) & (table["metric"] == "auprc")]

    baseline_name = (
        "coordinate_plus_frozen_sequence_fm"
        if task == "cCRE"
        else "coordinate_plus_frozen_sequence_fm_pair"
    )
    combined_name = (
        "coordinate_plus_frozen_sequence_fm_plus_frozen_pangenomefm"
        if task == "cCRE"
        else "coordinate_plus_frozen_sequence_fm_plus_frozen_pangenomefm_pair"
    )

    def one(feature_set: str, closure: str) -> pd.Series:
        rows = task_rows[
            (task_rows["feature_set"] == feature_set)
            & (task_rows["closure"] == closure)
        ]
        if len(rows) != 1:
            raise ValueError(
                f"Expected one {task}/{closure}/{feature_set} row; found {len(rows)}"
            )
        return rows.iloc[0]

    # The coordinate-plus-sequence baseline is identical across closures.
    baseline = one(baseline_name, "strict")
    strict = one(combined_name, "strict")
    one_hop = one(combined_name, "1hop")
    values = [float(baseline["mean"]), float(strict["mean"]), float(one_hop["mean"])]
    gains = [values[1] - values[0], values[2] - values[0]]
    return values, gains


def _gradient_bar(
    ax: mpl.axes.Axes,
    x: float,
    value: float,
    *,
    bottom: float,
    width: float,
    colors: tuple[str, str],
) -> None:
    height = value - bottom
    bar = ax.bar(
        x,
        height,
        bottom=bottom,
        width=width,
        color="none",
        edgecolor=colors[0],
        linewidth=1.0,
        zorder=3,
    )[0]
    gradient = np.linspace(0, 1, 256).reshape(256, 1)
    cmap = LinearSegmentedColormap.from_list("poster_bar", colors)
    image = ax.imshow(
        gradient,
        extent=(x - width / 2, x + width / 2, bottom, value),
        origin="lower",
        aspect="auto",
        cmap=cmap,
        interpolation="bicubic",
        zorder=2.8,
    )
    image.set_clip_path(bar)


def _build_chart(
    *,
    values: list[float],
    gains: list[float],
    title: str,
    subtitle: str,
    contribution: str,
    interpretation: str,
    output_stem: Path,
    dpi: int,
) -> None:
    # A wide, identical canvas lets the two charts drop into paired poster boxes.
    fig, ax = plt.subplots(figsize=(10.5, 5.6), constrained_layout=False)
    fig.patch.set_facecolor("white")
    ax.set_facecolor("white")

    x = np.arange(3)
    y_min, y_max = 0.70, 1.00
    width = 0.52
    for index, value in enumerate(values):
        colors = (
            (NEUTRAL_DARK, NEUTRAL_LIGHT)
            if index == 0
            else (TEMPLE_DARK, TEMPLE_CHERRY)
        )
        _gradient_bar(
            ax,
            float(index),
            value,
            bottom=y_min,
            width=width,
            colors=colors,
        )
        ax.text(
            index,
            value + 0.010,
            f"{value:.4f}",
            ha="center",
            va="bottom",
            fontsize=15,
            fontweight="bold",
            color=TEXT,
            clip_on=False,
        )

    ax.set_xlim(-0.60, 2.60)
    ax.set_ylim(y_min, y_max)
    ax.set_xticks(x)
    ax.set_xticklabels(
        [
            "Coordinates +\nsequence",
            "+ graph\n(strict context)",
            "+ graph\n(one-hop context)",
        ],
        fontsize=13,
        fontweight="semibold",
    )
    ax.set_yticks(np.arange(0.70, 1.001, 0.05))
    ax.yaxis.set_major_formatter(mpl.ticker.FormatStrFormatter("%.2f"))
    ax.tick_params(axis="y", labelsize=12, colors=TEXT)
    ax.tick_params(axis="x", length=0, pad=9, colors=TEXT)
    ax.set_ylabel("Mean chromosome-held-out AUPRC", fontsize=13, fontweight="bold")
    ax.grid(axis="y", color=GRID, linewidth=1.0, zorder=0)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.spines["left"].set_color("#555555")
    ax.spines["bottom"].set_color("#555555")

    fig.text(
        0.5,
        0.958,
        title,
        ha="center",
        va="top",
        fontsize=18,
        fontweight="bold",
        color=TEMPLE_CHERRY,
    )
    fig.text(
        0.5,
        0.905,
        subtitle,
        ha="center",
        va="top",
        fontsize=16,
        fontweight="bold",
        color=TEMPLE_CHERRY,
    )

    contribution_box = mpl.patches.FancyBboxPatch(
        (0.17, 0.070),
        0.66,
        0.075,
        transform=fig.transFigure,
        boxstyle="round,pad=0.004,rounding_size=0.008",
        linewidth=1.25,
        edgecolor=TEMPLE_LIGHT,
        facecolor="#FFF6F7",
    )
    fig.add_artist(contribution_box)
    fig.text(
        0.5,
        0.108,
        contribution,
        ha="center",
        va="center",
        fontsize=15,
        fontweight="bold",
        color=TEMPLE_CHERRY,
    )
    fig.text(
        0.5,
        0.030,
        interpretation,
        ha="center",
        va="center",
        fontsize=12.5,
        color=TEXT,
    )
    fig.subplots_adjust(left=0.13, right=0.975, top=0.82, bottom=0.25)

    # Keep the range text source-driven even though the poster uses rounded values.
    expected = f"+{min(gains):.3f}\N{EN DASH}{max(gains):.3f} AUPRC"
    if expected not in contribution:
        raise ValueError(f"Contribution label {contribution!r} does not match {expected!r}")

    output_stem.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_stem.with_suffix(".png"), dpi=dpi, facecolor="white")
    fig.savefig(output_stem.with_suffix(".pdf"), facecolor="white")
    plt.close(fig)


def main() -> int:
    args = _parser().parse_args()
    source = args.source.resolve()
    output_dir = args.output_dir.resolve()
    ccre_values, ccre_gains = _read_values(source, "cCRE")
    sv_values, sv_gains = _read_values(source, "SV")

    _build_chart(
        values=ccre_values,
        gains=ccre_gains,
        title="Graph representations add complementary regulatory information",
        subtitle="Candidate regulatory-region classification",
        contribution="Graph contribution: +0.003\N{EN DASH}0.004 AUPRC",
        interpretation="Small but reproducible gain beyond coordinates and sequence.",
        output_stem=output_dir / "poster_ccre_graph_contribution",
        dpi=args.dpi,
    )
    _build_chart(
        values=sv_values,
        gains=sv_gains,
        title="Graph representations contribute strongly to SV breakpoint prediction",
        subtitle="Structural-variant breakpoint classification",
        contribution="Graph contribution: +0.034\N{EN DASH}0.040 AUPRC",
        interpretation="A substantially larger contribution than in the cCRE task.",
        output_stem=output_dir / "poster_sv_graph_contribution",
        dpi=args.dpi,
    )

    print(f"Wrote: {output_dir / 'poster_ccre_graph_contribution.png'}")
    print(f"Wrote: {output_dir / 'poster_sv_graph_contribution.png'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
